export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
export const SET_CART_OPTIONS = "SET_CART_OPTIONS";
export const UPDATE_CART_OPTIONS = "UPDATE_CART_OPTIONS";

export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_LOADING = "SET_LOADING";
export const PLACE_ORDER = "PLACE_ORDER";
export const SEND_CONFIRMATION = "SEND_CONFIRMATION";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
